/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package financetracker;

import java.awt.Color;
import java.awt.Font;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JOptionPane;


/**
 *
 * @author DELL
 */
public class dashnew1 extends javax.swing.JFrame {
    
    private double balance = 0.0;
    String acc_no = "";
    String to_acc = "0";
    String ac = "";

    public dashnew1(String accno) {
        initComponents();
        jTable1.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        jTable1.getTableHeader().setOpaque(false);
        jTable1.getTableHeader().setBackground(new Color(32, 136, 203));
        jTable1.setRowHeight(25);
        acc_no = accno;
        jTextField9.setText(databaseconnection.getUserName(accno));
        balshow.setText(Double.toString(databaseconnection.getBalance(accno)));
        LocalDate currentDate = LocalDate.now();
        displayTransactions(accno, String.valueOf(currentDate.getYear()), currentDate.getMonth().toString().substring(0, 3), String.valueOf(currentDate.getDayOfMonth()), "Expense");

        String iiid = String.valueOf(currentDate.getYear()) + currentDate.getMonth().toString().substring(0, 3) + acc_no;
        sr_y_combo.setSelectedItem(String.valueOf(currentDate.getYear()));
        sr_m_combo.setSelectedItem(currentDate.getMonth().toString().substring(0, 3));
        sr_d_combo.setSelectedItem(String.valueOf(currentDate.getDayOfMonth()));

        budgett();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        parent = new javax.swing.JPanel();
        dash = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        balshow = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        sr_ty_combo = new javax.swing.JComboBox<>();
        sr_m_combo = new javax.swing.JComboBox<>();
        sr_d_combo = new javax.swing.JComboBox<>();
        sr_y_combo = new javax.swing.JComboBox<>();
        jButton15 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        options = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        income = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        idate_txt_y = new javax.swing.JTextField();
        iamount_txt = new javax.swing.JTextField();
        icategory_slct = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton12 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        idate_txt_m = new javax.swing.JTextField();
        idate_txt_d = new javax.swing.JTextField();
        transfer = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tdate_txt_y = new javax.swing.JTextField();
        to_acc_txt = new javax.swing.JTextField();
        tamount_txt = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton13 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        note_txt = new javax.swing.JTextField();
        tdate_txt_d = new javax.swing.JTextField();
        tdate_txt_m = new javax.swing.JTextField();
        ex = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        edate_txt_y = new javax.swing.JTextField();
        eamount_txt = new javax.swing.JTextField();
        ecategory_slct = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jButton14 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        edate_txt_d = new javax.swing.JTextField();
        edate_txt_m = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        budget_txt = new javax.swing.JLabel();
        jButton16 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        t_expences_txt = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        t_incomes_txt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(226, 223, 198));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton8.setBackground(new java.awt.Color(254, 146, 161));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Finance_Tracker/add.png"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 60, 60));

        jButton9.setBackground(new java.awt.Color(255, 176, 163));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Finance_Tracker/home.png"))); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 50, 50));

        jButton10.setBackground(new java.awt.Color(166, 123, 180));
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Finance_Tracker/bx-bar-chart-square.png"))); // NOI18N
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 50, 50));
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 490, 70));

        jLabel21.setText("Loading...");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, 972, -1));

        parent.setBackground(new java.awt.Color(255, 255, 255));
        parent.setLayout(new java.awt.CardLayout());

        dash.setBackground(new java.awt.Color(255, 255, 255));
        dash.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setText("Balance : ");
        dash.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, -1, -1));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabel3.setText("welcome");
        dash.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 90, 30));

        balshow.setEditable(false);
        balshow.setBackground(new java.awt.Color(231, 222, 201));
        dash.add(balshow, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 150, 30));

        jTextField9.setEditable(false);
        jTextField9.setBackground(new java.awt.Color(202, 200, 200));
        jTextField9.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        dash.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 150, 30));

        sr_ty_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Expense", "Income", "Transfer" }));
        dash.add(sr_ty_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, -1, -1));

        sr_m_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "JAN", "FEB", "MAR", "APR", "MAY", "JUN", "JUL", "AUG", "SEP", "OCT", "NOV", "DEC" }));
        dash.add(sr_m_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, -1, -1));

        sr_d_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        dash.add(sr_d_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, -1, -1));

        sr_y_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2020", "2021", "2022", "2023", "2024" }));
        dash.add(sr_y_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        jButton15.setText("Search");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        dash.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Finance_Tracker/balence.png"))); // NOI18N
        dash.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, -90, 560, 500));

        jTable1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Note", "Amount(Rs.)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setFocusable(false);
        jTable1.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTable1.setRowHeight(20);
        jTable1.setShowVerticalLines(false);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        dash.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 490, 240));

        parent.add(dash, "card2");

        options.setBackground(new java.awt.Color(255, 255, 255));
        options.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("jButton1");
        options.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 831, -1, -1));

        jButton2.setBackground(new java.awt.Color(159, 201, 221));
        jButton2.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jButton2.setText("Transfer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        options.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 460, 220, 120));

        jButton3.setBackground(new java.awt.Color(159, 201, 221));
        jButton3.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jButton3.setText("Income");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        options.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 220, 120));

        jButton4.setBackground(new java.awt.Color(159, 201, 221));
        jButton4.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jButton4.setText("Expense");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        options.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 220, 120));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Finance_Tracker/up.jpg"))); // NOI18N
        options.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -290, 490, 360));

        parent.add(options, "card3");

        income.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel6.setText("Date :");

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel7.setText("Category :");

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel8.setText("Amount :");

        icategory_slct.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        icategory_slct.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Allowance", "Salary", "Petty Cash", "Bonus" }));

        jButton5.setBackground(new java.awt.Color(177, 177, 177));
        jButton5.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jButton5.setText("add");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton12.setBackground(new java.awt.Color(255, 182, 169));
        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Finance_Tracker/bx-arrow-back.png"))); // NOI18N
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Finance_Tracker/income.jpg"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 414, 361));

        javax.swing.GroupLayout incomeLayout = new javax.swing.GroupLayout(income);
        income.setLayout(incomeLayout);
        incomeLayout.setHorizontalGroup(
            incomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
            .addGroup(incomeLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(incomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(incomeLayout.createSequentialGroup()
                        .addGroup(incomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(incomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(icategory_slct, 0, 223, Short.MAX_VALUE)
                            .addComponent(iamount_txt)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, incomeLayout.createSequentialGroup()
                                .addComponent(idate_txt_y, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idate_txt_m)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idate_txt_d, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(70, 70, 70))
        );
        incomeLayout.setVerticalGroup(
            incomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, incomeLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(incomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(idate_txt_y, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idate_txt_m, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idate_txt_d, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(incomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(icategory_slct, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(incomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(iamount_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(44, 44, 44))
        );

        parent.add(income, "card4");

        transfer.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel12.setText("To :");

        jLabel13.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel13.setText("Amount :");

        jLabel14.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel14.setText("Date :");

        tdate_txt_y.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tdate_txt_yActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jButton7.setText("Add");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton13.setBackground(new java.awt.Color(255, 182, 169));
        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Finance_Tracker/bx-arrow-back.png"))); // NOI18N
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Finance_Tracker/tra.png"))); // NOI18N
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 32, -1, 338));

        jButton11.setBackground(new java.awt.Color(102, 102, 255));
        jButton11.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButton11.setText("Search");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel17.setText("Note :");

        tdate_txt_d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tdate_txt_dActionPerformed(evt);
            }
        });

        tdate_txt_m.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tdate_txt_mActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout transferLayout = new javax.swing.GroupLayout(transfer);
        transfer.setLayout(transferLayout);
        transferLayout.setHorizontalGroup(
            transferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(transferLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(transferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(transferLayout.createSequentialGroup()
                        .addGroup(transferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13)
                            .addComponent(jLabel17))
                        .addGap(30, 30, 30)
                        .addGroup(transferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(transferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tamount_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                                .addComponent(note_txt))
                            .addGroup(transferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(transferLayout.createSequentialGroup()
                                    .addComponent(tdate_txt_y)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tdate_txt_m, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tdate_txt_d, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(transferLayout.createSequentialGroup()
                                    .addComponent(to_acc_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton11))))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        transferLayout.setVerticalGroup(
            transferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, transferLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(transferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tdate_txt_y, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tdate_txt_d, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tdate_txt_m, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(transferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(transferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(to_acc_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton11)))
                .addGap(18, 18, 18)
                .addGroup(transferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tamount_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(transferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(note_txt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jButton7)
                .addGap(38, 38, 38))
        );

        parent.add(transfer, "card6");

        ex.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel9.setText("Date :");

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel10.setText("Category :");

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel11.setText("amount :");

        jButton6.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jButton6.setText("Add");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        eamount_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eamount_txtActionPerformed(evt);
            }
        });

        ecategory_slct.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        ecategory_slct.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Food", "Transport", "Household", "Health", "Education", "Apparel", "Beauty", "Gift" }));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton14.setBackground(new java.awt.Color(255, 182, 169));
        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Finance_Tracker/bx-arrow-back.png"))); // NOI18N
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Finance_Tracker/New expens.png"))); // NOI18N
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 13, 387, 370));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 170, 10));

        edate_txt_d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edate_txt_dActionPerformed(evt);
            }
        });

        edate_txt_m.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edate_txt_mActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout exLayout = new javax.swing.GroupLayout(ex);
        ex.setLayout(exLayout);
        exLayout.setHorizontalGroup(
            exLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(exLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(exLayout.createSequentialGroup()
                        .addGroup(exLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(exLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(exLayout.createSequentialGroup()
                                .addComponent(edate_txt_y, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edate_txt_m, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edate_txt_d, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                            .addComponent(ecategory_slct, 0, 226, Short.MAX_VALUE)
                            .addComponent(eamount_txt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)))
                .addGap(48, 48, 48))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
        );
        exLayout.setVerticalGroup(
            exLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(exLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(edate_txt_y, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edate_txt_m, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edate_txt_d, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(exLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(ecategory_slct, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(exLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(eamount_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(33, 33, 33))
        );

        parent.add(ex, "card5");

        getContentPane().add(parent, new org.netbeans.lib.awtextra.AbsoluteConstraints(484, 0, 488, 634));

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel18.setText("Monthly Budget");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jPanel5.setBackground(new java.awt.Color(153, 153, 255));

        budget_txt.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        budget_txt.setText("Rs. -");

        jButton16.setText("Set");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(127, Short.MAX_VALUE)
                .addComponent(budget_txt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(jButton16)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(budget_txt)
                    .addComponent(jButton16))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 310, 80));

        jLabel22.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel22.setText("Total Expences");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, -1, -1));

        jPanel6.setBackground(new java.awt.Color(255, 51, 50));

        t_expences_txt.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        t_expences_txt.setText("Rs. -");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(127, Short.MAX_VALUE)
                .addComponent(t_expences_txt)
                .addContainerGap(127, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(t_expences_txt)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 310, 80));

        jLabel24.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel24.setText("Total Incomes");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, -1, -1));

        jPanel7.setBackground(new java.awt.Color(0, 204, 0));

        t_incomes_txt.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        t_incomes_txt.setText("Rs. -");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(127, Short.MAX_VALUE)
                .addComponent(t_incomes_txt)
                .addContainerGap(127, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(t_incomes_txt)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, 310, 80));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        LocalDate currentDate = LocalDate.now();
        
        // Get the year, month (short form), and date separately
        edate_txt_y.setText(String.valueOf(currentDate.getYear()));
        edate_txt_m.setText(currentDate.getMonth().toString().substring(0, 3));
        edate_txt_d.setText(String.valueOf(currentDate.getDayOfMonth()));
        
        parent.removeAll();
    parent.add(ex);
    parent.repaint ();
    parent.revalidate();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        LocalDate currentDate = LocalDate.now();
        
        // Get the year, month (short form), and date separately
        idate_txt_y.setText(String.valueOf(currentDate.getYear()));
        idate_txt_m.setText(currentDate.getMonth().toString().substring(0, 3));
        idate_txt_d.setText(String.valueOf(currentDate.getDayOfMonth()));
        
        
        parent.removeAll();
    parent.add(income);
    parent.repaint ();
    parent.revalidate();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        addETransaction();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    parent.removeAll();
    parent.add(options);
    parent.repaint ();
    parent.revalidate();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        LocalDate currentDate = LocalDate.now();
        
        // Get the year, month (short form), and date separately
        tdate_txt_y.setText(String.valueOf(currentDate.getYear()));
        tdate_txt_m.setText(currentDate.getMonth().toString().substring(0, 3));
        tdate_txt_d.setText(String.valueOf(currentDate.getDayOfMonth()));
        
        parent.removeAll();
    parent.add(transfer);
    parent.repaint ();
    parent.revalidate();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        parent.removeAll();
    parent.add(dash);
    parent.repaint ();
    parent.revalidate();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        report r = new report(acc_no);
        r.setVisible(true);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
        addITransaction();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void eamount_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eamount_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eamount_txtActionPerformed

    private void tdate_txt_yActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tdate_txt_yActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tdate_txt_yActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        parent.removeAll();
    parent.add(options);
    parent.repaint ();
    parent.revalidate();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        parent.removeAll();
    parent.add(options);
    parent.repaint ();
    parent.revalidate();
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        parent.removeAll();
    parent.add(options);
    parent.repaint ();
    parent.revalidate();
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        String un = databaseconnection.getUserName(to_acc_txt.getText());
        
        if(un!="Wrong Account Number!")
        {
            ac = to_acc_txt.getText();
            to_acc_txt.setText(un);
        }
        else
        {
            to_acc_txt.setText(un);
        }
       
        
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        String y = tdate_txt_y.getText();
        String m = tdate_txt_m.getText();
        String d = tdate_txt_d.getText();
        String too_accc = ac;
        String note = note_txt.getText();
        double amount = Double.parseDouble(tamount_txt.getText());
        String type = "Transfer";
        
        
        String tid_n = String.valueOf(databaseconnection.getrownumbers("tra"));
        String tid = "T000"+tid_n;
       
        
        LocalDateTime currentDateTime = LocalDateTime.now();
        String dateTime = currentDateTime.toString();
        


        // Insert the transaction into the database
        
        databaseconnection.insertTransaction(tid, note, amount, type, acc_no, too_accc, y, m, d);
        databaseconnection.updateBalance(acc_no, amount, 1);
        databaseconnection.updateBalance(too_accc, amount, 0);
        LocalDate currentDate = LocalDate.now();
        databaseconnection.updatetexpences(String.valueOf(currentDate.getYear())+currentDate.getMonth().toString().substring(0, 3)+acc_no, amount);
        
        t_expences_txt.setText("Rs. "+Double.toString(databaseconnection.gettexpences(String.valueOf(currentDate.getYear())+currentDate.getMonth().toString().substring(0, 3)+acc_no)));
        
//        displayTransactions(acc_no, String.valueOf(currentDate.getYear()), currentDate.getMonth().toString().substring(0, 3), String.valueOf(currentDate.getDayOfMonth()), "");
        balshow.setText(Double.toString(databaseconnection.getBalance(acc_no)));
        JOptionPane.showMessageDialog(this, "Transaction add successful.", "Success", JOptionPane.INFORMATION_MESSAGE);

        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
//        parent.removeAll();
//        if(sr_ty_combo.getSelectedItem().toString()=="Expense")
//        {
//            parent.add(ex);
//            parent.repaint ();
//            parent.revalidate();
//        }
//        else if(sr_ty_combo.getSelectedItem().toString()=="Income")
//        {
//            parent.add(income);
//            parent.repaint ();
//            parent.revalidate();
//        }
        
        
        
        explore ex = new explore((String) jTable1.getValueAt(jTable1.getSelectedRow(), 0));
        ex.setVisible(true);
        
        System.out.println(jTable1.getValueAt(jTable1.getSelectedRow(), 0));
        
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
       budget b = new budget(acc_no, this);
    b.setVisible(true);
        
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        
                displayTransactions(acc_no, sr_y_combo.getSelectedItem().toString(), sr_m_combo.getSelectedItem().toString(), sr_d_combo.getSelectedItem().toString(), sr_ty_combo.getSelectedItem().toString());

        
    }//GEN-LAST:event_jButton15ActionPerformed

    private void tdate_txt_dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tdate_txt_dActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tdate_txt_dActionPerformed

    private void tdate_txt_mActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tdate_txt_mActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tdate_txt_mActionPerformed

    private void edate_txt_dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edate_txt_dActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edate_txt_dActionPerformed

    private void edate_txt_mActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edate_txt_mActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edate_txt_mActionPerformed

    void displayTransactions(String acc, String y, String m, String d, String type) {
        
        
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                while (model.getRowCount() > 0) {
                model.removeRow(0);
                    }
                
//        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        
        List<List<Object>> transactions = databaseconnection.getTransactions(acc ,y ,m , d, type);
        for (List<Object> transaction : transactions) {
            model.addRow(transaction.toArray());
        }
    }
    
    private void addITransaction() {
        // Get the values from the input fields
        
        
                
        String y = idate_txt_y.getText();
        String m = idate_txt_m.getText();
        String d = idate_txt_d.getText();
        String category = (String) icategory_slct.getSelectedItem();
        String type = "Income";
        double amount = Double.parseDouble(iamount_txt.getText());
        String tid = "";
        String tid_n = String.valueOf(databaseconnection.getrownumbers("tra"));
        if(type == "Income")
        {
            databaseconnection.updateBalance(acc_no, amount, 0);
            tid = "I000"+tid_n;
        }
        else if(type == "Expense")
        {
            databaseconnection.updateBalance(acc_no, amount, 1);
            tid = "E000"+tid_n;
        }
        
        LocalDateTime currentDateTime = LocalDateTime.now();
        String dateTime = currentDateTime.toString();
        


        // Insert the transaction into the database
        
        databaseconnection.insertTransaction(tid, category, amount, type, acc_no, to_acc, y, m, d);
        
        LocalDate currentDate = LocalDate.now();
        databaseconnection.updatetincomes(String.valueOf(currentDate.getYear())+currentDate.getMonth().toString().substring(0, 3)+acc_no, amount);

        t_incomes_txt.setText("Rs. "+Double.toString(databaseconnection.gettincomes(String.valueOf(currentDate.getYear())+currentDate.getMonth().toString().substring(0, 3)+acc_no)));

        
        // Update the balance
        balshow.setText(Double.toString(databaseconnection.getBalance(acc_no)));
        
        
//        displayTransactions(acc_no);
        
        // Clear input fields
//        idate_txt_y.setText("");
        iamount_txt.setText("");
        JOptionPane.showMessageDialog(this, "Transaction add successful.", "Success", JOptionPane.INFORMATION_MESSAGE);

        
    }
    
    private void addETransaction() {
        // Get the values from the input fields
        
        
                
        String y = edate_txt_y.getText();
        String m = edate_txt_m.getText();
        String d = edate_txt_d.getText();
        String category = (String) ecategory_slct.getSelectedItem();
        String type = "Expense";
        double amount = Double.parseDouble(eamount_txt.getText());
        String tid = "";
        String tid_n = String.valueOf(databaseconnection.getrownumbers("tra"));
        if(type == "Income")
        {
            databaseconnection.updateBalance(acc_no, amount, 0);
            tid = "I000"+tid_n;
        }
        else if(type == "Expense")
        {
            databaseconnection.updateBalance(acc_no, amount, 1);
            tid = "E000"+tid_n;
        }
        
        LocalDateTime currentDateTime = LocalDateTime.now();
        String dateTime = currentDateTime.toString();
        


        // Insert the transaction into the database
        
        databaseconnection.insertTransaction(tid, category, amount, type, acc_no, to_acc, y, m, d);
        LocalDate currentDate = LocalDate.now();
        databaseconnection.updatetexpences(String.valueOf(currentDate.getYear())+currentDate.getMonth().toString().substring(0, 3)+acc_no, amount);
        t_expences_txt.setText("Rs. "+Double.toString(databaseconnection.gettexpences(String.valueOf(currentDate.getYear())+currentDate.getMonth().toString().substring(0, 3)+acc_no)));
        
        // Update the balance
        balshow.setText(Double.toString(databaseconnection.getBalance(acc_no)));
        
        
//        displayTransactions(acc_no);
        
        // Clear input fields
//        edate_txt_y.setText("");
        eamount_txt.setText("");
        JOptionPane.showMessageDialog(this, "Transaction add successful.", "Success", JOptionPane.INFORMATION_MESSAGE);

        
    }
    
    
    public void budgett() {
        
        LocalDate currentDate = LocalDate.now();
        String iiid = String.valueOf(currentDate.getYear()) + currentDate.getMonth().toString().substring(0, 3) + acc_no;
        Timer timer = new Timer();
        long delay = 1000; // 1 second

        timer.schedule(new TimerTask() {
            public void run() {
                if (!databaseconnection.budgetcheck(iiid)) {
                    budget b = new budget(acc_no, dashnew1.this); // Pass the current instance of dashnew1
                    b.setVisible(true);
                } else {
                    budget_txt.setText("Rs. " + Double.toString(databaseconnection.getBudget(iiid)));
                    t_incomes_txt.setText("Rs. " + Double.toString(databaseconnection.gettincomes(iiid)));
                    t_expences_txt.setText("Rs. " + Double.toString(databaseconnection.gettexpences(iiid)));
                }
                jLabel21.setText("Online");
                timer.cancel();
            }
        }, delay);
          
        
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        String ac="";
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashnew1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashnew1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashnew1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashnew1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashnew1(ac).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField balshow;
    private javax.swing.JLabel budget_txt;
    private javax.swing.JPanel dash;
    private javax.swing.JTextField eamount_txt;
    private javax.swing.JComboBox<String> ecategory_slct;
    private javax.swing.JTextField edate_txt_d;
    private javax.swing.JTextField edate_txt_m;
    private javax.swing.JTextField edate_txt_y;
    private javax.swing.JPanel ex;
    private javax.swing.JTextField iamount_txt;
    private javax.swing.JComboBox<String> icategory_slct;
    private javax.swing.JTextField idate_txt_d;
    private javax.swing.JTextField idate_txt_m;
    private javax.swing.JTextField idate_txt_y;
    private javax.swing.JPanel income;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField note_txt;
    private javax.swing.JPanel options;
    private javax.swing.JPanel parent;
    private javax.swing.JComboBox<String> sr_d_combo;
    private javax.swing.JComboBox<String> sr_m_combo;
    private javax.swing.JComboBox<String> sr_ty_combo;
    private javax.swing.JComboBox<String> sr_y_combo;
    private javax.swing.JLabel t_expences_txt;
    private javax.swing.JLabel t_incomes_txt;
    private javax.swing.JTextField tamount_txt;
    private javax.swing.JTextField tdate_txt_d;
    private javax.swing.JTextField tdate_txt_m;
    private javax.swing.JTextField tdate_txt_y;
    private javax.swing.JTextField to_acc_txt;
    private javax.swing.JPanel transfer;
    // End of variables declaration//GEN-END:variables
}
