/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package financetracker;

import javax.swing.JOptionPane;

/**
 *
 * @author TM Sachith
 */
public class explore extends javax.swing.JFrame {

    /**
     * Creates new form explore
     */
    String acc_no = "";
    
    public explore(String acc) {
        
        acc_no = acc;
        setTitle(acc_no);
        initComponents();
        loadTransactionData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        amount_lbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        status_lbl = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        datetime_lbl = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        note_lbl = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        to_lbl = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        type_lbl = new javax.swing.JLabel();
        toname_lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        amount_lbl.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        amount_lbl.setText("Rs. 1800.0");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("Transaction Details");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setText("Status : ");

        status_lbl.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        status_lbl.setText("Success");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setText("Date : ");

        datetime_lbl.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        datetime_lbl.setText("Success");

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel7.setText("Note :");

        note_lbl.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        note_lbl.setText("Success");

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel9.setText("To :");

        to_lbl.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        to_lbl.setText("Success");

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel12.setText("Type :");

        type_lbl.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        type_lbl.setText("Success");

        toname_lbl.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel2)
                        .addGap(0, 75, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(status_lbl)
                                .addComponent(datetime_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(type_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(note_lbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(amount_lbl))
                            .addComponent(to_lbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(toname_lbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addGap(32, 32, 32)
                .addComponent(amount_lbl)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(type_lbl))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(status_lbl))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(datetime_lbl))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(note_lbl))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(to_lbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(toname_lbl)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    private void loadTransactionData() {
        Object[] transactionData = databaseconnection.getTransactionByAccount(acc_no);
        if (transactionData != null) {
            // Assuming the transactionData array has columns in the following order:
            // id, note, amount, type, from_acc, to_acc, year, month, date, datetime, status
            type_lbl.setText((String) transactionData[4]);
            datetime_lbl.setText((String) transactionData[8]+" "+(String) transactionData[9]+" "+(String) transactionData[10]);
//            jLabel6.setText(transactionData[9].toString()); // Assuming datetime is at index 9
            note_lbl.setText((String) transactionData[2]);
            
            to_lbl.setText(Integer.toString((Integer) transactionData[6]));
//            if(transactionData[6].toString() == "0")
//            {
//                to_lbl.setText("-");
//            }
//            else
//            {
//                to_lbl.setText(Integer.toString((Integer) transactionData[6]));
//                toname_lbl.setText(databaseconnection.getUserName(Integer.toString((Integer) transactionData[6])));
//            }
            
            
            amount_lbl.setText("Rs. "+ Double.toString((Double) transactionData[3]));

            
//            amount_lbl.setText("Rs. " + transactionData[2].toString());

            System.out.println(acc_no);
            System.out.println((String) transactionData[4]);
        } else {
            JOptionPane.showMessageDialog(this, "No transaction found for account number " + acc_no);
        }
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(explore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(explore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(explore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(explore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        
        
        String ac="";
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new explore(ac).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amount_lbl;
    private javax.swing.JLabel datetime_lbl;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel note_lbl;
    private javax.swing.JLabel status_lbl;
    private javax.swing.JLabel to_lbl;
    private javax.swing.JLabel toname_lbl;
    private javax.swing.JLabel type_lbl;
    // End of variables declaration//GEN-END:variables
}
