/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package financetracker;

import javax.swing.JOptionPane;
import java.security.NoSuchAlgorithmException;  
import java.security.MessageDigest;  
/**
 *
 * @author DELL
 */
public class signup extends javax.swing.JFrame {

    /**
     * Creates new form signup
     */
    public signup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        name_txt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        dob_txt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        email_txt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        nic_txt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sign Up Page");
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setMaximumSize(null);
        jPanel3.setPreferredSize(new java.awt.Dimension(487, 694));
        jPanel3.setLayout(null);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Finance_Tracker/signup.jpg"))); // NOI18N
        jPanel3.add(jLabel8);
        jLabel8.setBounds(35, 54, 350, 313);

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel2.setText("Name :");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(55, 385, 54, 21);

        name_txt.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        name_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_txtActionPerformed(evt);
            }
        });
        jPanel3.add(name_txt);
        name_txt.setBounds(240, 385, 212, 28);

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel3.setText("Date of Birth :");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(55, 427, 105, 21);

        dob_txt.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        dob_txt.setMinimumSize(new java.awt.Dimension(6, 27));
        dob_txt.setPreferredSize(new java.awt.Dimension(6, 27));
        jPanel3.add(dob_txt);
        dob_txt.setBounds(240, 425, 212, 28);

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel7.setText("Email :");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(55, 469, 52, 21);

        email_txt.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        email_txt.setMinimumSize(new java.awt.Dimension(6, 28));
        email_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_txtActionPerformed(evt);
            }
        });
        jPanel3.add(email_txt);
        email_txt.setBounds(240, 465, 212, 28);

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel4.setText("Password :");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(55, 550, 87, 21);

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel5.setText("Confirm Password :");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(55, 588, 152, 21);

        jButton1.setBackground(new java.awt.Color(102, 153, 255));
        jButton1.setFont(new java.awt.Font("SansSerif", 1, 17)); // NOI18N
        jButton1.setText("Create");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(55, 632, 400, 33);

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel6.setText("NIC :");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(55, 508, 38, 21);

        nic_txt.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        nic_txt.setMinimumSize(new java.awt.Dimension(6, 28));
        nic_txt.setPreferredSize(new java.awt.Dimension(6, 28));
        nic_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nic_txtActionPerformed(evt);
            }
        });
        jPanel3.add(nic_txt);
        nic_txt.setBounds(240, 505, 212, 28);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabel1.setText("Create your Account");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(144, 4, 195, 26);

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 51));
        jLabel9.setText("Already have an Account? ");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(60, 680, 186, 30);

        jButton2.setBackground(new java.awt.Color(0, 51, 102));
        jButton2.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Sign in");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(370, 680, 83, 30);

        jPasswordField1.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        jPanel3.add(jPasswordField1);
        jPasswordField1.setBounds(240, 545, 212, 28);

        jPasswordField2.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        jPanel3.add(jPasswordField2);
        jPasswordField2.setBounds(240, 585, 212, 28);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 728, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void email_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_txtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String name = name_txt.getText();
        String dob = dob_txt.getText();
        String nic = nic_txt.getText();
        String email = email_txt.getText();
        char[] passwordChars = jPasswordField1.getPassword();
        String password = new String(passwordChars);
        char[] passwordChars2 = jPasswordField2.getPassword();
        String confirmPassword = new String(passwordChars2);
        
        double bal = 0.0;
        //----------------------------
         
        String encryptedpassword = FinanceTracker.encry(confirmPassword);
        //--------------------------------
        
        
        int accno = 10000 + databaseconnection.getrownumbers("users");

        if (!password.equals(confirmPassword)) {
            
            JOptionPane.showMessageDialog(this, "Passwords do not match!", "Error", JOptionPane.ERROR_MESSAGE);
            
            // Passwords do not match
            // Display an error message
            
        } else {
            
            if(databaseconnection.niccheck(nic))
            {
               JOptionPane.showMessageDialog(this, "Entered NIC is already used!", "Error", JOptionPane.ERROR_MESSAGE); 
            }
            else
            {
                // Passwords match, insert the user into the database
            databaseconnection.insertUser(accno, name, nic, dob, email, encryptedpassword , bal);
            // User added successfully, you can close the signup window or navigate to another page
            
            this.dispose(); // Close the signup window
            login login = new login();
            login.setVisible(true);
            }
            
            
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void name_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_txtActionPerformed

    private void nic_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nic_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nic_txtActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
         login lo = new login();
            lo.setVisible(true);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dob_txt;
    private javax.swing.JTextField email_txt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField name_txt;
    private javax.swing.JTextField nic_txt;
    // End of variables declaration//GEN-END:variables
}
